spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: 2003
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8002


eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
