spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb+srv://mohammadhzbib:0OUqJLQne2gjIF6Q@production.xfmi3.mongodb.net/yourDatabase?retryWrites=true&w=majority&appName=production
server:
  port: 8001


eureka:
  client:
    service-url:
      default-one: http://localhost:8761/eureka